// Code generated by MockGen. DO NOT EDIT.
// Source: kubeletconfigs_client.go
//
// Generated by this command:
//
//	mockgen -source=kubeletconfigs_client.go -package=test -destination=test/mock_kubeletconfigs_client.go
//

// Package test is a generated GoMock package.
package test

import (
	context "context"
	reflect "reflect"

	client "github.com/openshift-online/ocm-common/pkg/ocm/client"
	v1 "github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockKubeletConfigsClient is a mock of KubeletConfigsClient interface.
type MockKubeletConfigsClient struct {
	ctrl     *gomock.Controller
	recorder *MockKubeletConfigsClientMockRecorder
}

// MockKubeletConfigsClientMockRecorder is the mock recorder for MockKubeletConfigsClient.
type MockKubeletConfigsClientMockRecorder struct {
	mock *MockKubeletConfigsClient
}

// NewMockKubeletConfigsClient creates a new mock instance.
func NewMockKubeletConfigsClient(ctrl *gomock.Controller) *MockKubeletConfigsClient {
	mock := &MockKubeletConfigsClient{ctrl: ctrl}
	mock.recorder = &MockKubeletConfigsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKubeletConfigsClient) EXPECT() *MockKubeletConfigsClientMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockKubeletConfigsClient) Create(ctx context.Context, clusterId string, instance *v1.KubeletConfig) (*v1.KubeletConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, clusterId, instance)
	ret0, _ := ret[0].(*v1.KubeletConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockKubeletConfigsClientMockRecorder) Create(ctx, clusterId, instance any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockKubeletConfigsClient)(nil).Create), ctx, clusterId, instance)
}

// Delete mocks base method.
func (m *MockKubeletConfigsClient) Delete(ctx context.Context, clusterId, instanceId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, clusterId, instanceId)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockKubeletConfigsClientMockRecorder) Delete(ctx, clusterId, instanceId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockKubeletConfigsClient)(nil).Delete), ctx, clusterId, instanceId)
}

// Exists mocks base method.
func (m *MockKubeletConfigsClient) Exists(ctx context.Context, clusterId, instanceId string) (bool, *v1.KubeletConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, clusterId, instanceId)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(*v1.KubeletConfig)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Exists indicates an expected call of Exists.
func (mr *MockKubeletConfigsClientMockRecorder) Exists(ctx, clusterId, instanceId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockKubeletConfigsClient)(nil).Exists), ctx, clusterId, instanceId)
}

// Get mocks base method.
func (m *MockKubeletConfigsClient) Get(ctx context.Context, clusterId, instanceId string) (*v1.KubeletConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, clusterId, instanceId)
	ret0, _ := ret[0].(*v1.KubeletConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockKubeletConfigsClientMockRecorder) Get(ctx, clusterId, instanceId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockKubeletConfigsClient)(nil).Get), ctx, clusterId, instanceId)
}

// List mocks base method.
func (m *MockKubeletConfigsClient) List(ctx context.Context, clusterId string, paging client.Paging) ([]*v1.KubeletConfig, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, clusterId, paging)
	ret0, _ := ret[0].([]*v1.KubeletConfig)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockKubeletConfigsClientMockRecorder) List(ctx, clusterId, paging any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockKubeletConfigsClient)(nil).List), ctx, clusterId, paging)
}

// Update mocks base method.
func (m *MockKubeletConfigsClient) Update(ctx context.Context, clusterId string, instance *v1.KubeletConfig) (*v1.KubeletConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, clusterId, instance)
	ret0, _ := ret[0].(*v1.KubeletConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockKubeletConfigsClientMockRecorder) Update(ctx, clusterId, instance any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockKubeletConfigsClient)(nil).Update), ctx, clusterId, instance)
}
