// Code generated by MockGen. DO NOT EDIT.
// Source: nodepool_client.go
//
// Generated by this command:
//
//	mockgen -source=nodepool_client.go -package=test -destination=test/mock_nodepool_client.go
//
// Package test is a generated GoMock package.
package test

import (
	context "context"
	reflect "reflect"

	client "github.com/openshift-online/ocm-common/pkg/ocm/client"
	v1 "github.com/openshift-online/ocm-sdk-go/clustersmgmt/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockNodePoolClient is a mock of NodePoolClient interface.
type MockNodePoolClient struct {
	ctrl     *gomock.Controller
	recorder *MockNodePoolClientMockRecorder
}

// MockNodePoolClientMockRecorder is the mock recorder for MockNodePoolClient.
type MockNodePoolClientMockRecorder struct {
	mock *MockNodePoolClient
}

// NewMockNodePoolClient creates a new mock instance.
func NewMockNodePoolClient(ctrl *gomock.Controller) *MockNodePoolClient {
	mock := &MockNodePoolClient{ctrl: ctrl}
	mock.recorder = &MockNodePoolClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNodePoolClient) EXPECT() *MockNodePoolClientMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockNodePoolClient) Create(ctx context.Context, clusterId string, instance *v1.NodePool) (*v1.NodePool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, clusterId, instance)
	ret0, _ := ret[0].(*v1.NodePool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockNodePoolClientMockRecorder) Create(ctx, clusterId, instance any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockNodePoolClient)(nil).Create), ctx, clusterId, instance)
}

// Delete mocks base method.
func (m *MockNodePoolClient) Delete(ctx context.Context, clusterId, instanceId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, clusterId, instanceId)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockNodePoolClientMockRecorder) Delete(ctx, clusterId, instanceId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockNodePoolClient)(nil).Delete), ctx, clusterId, instanceId)
}

// Exists mocks base method.
func (m *MockNodePoolClient) Exists(ctx context.Context, clusterId, instanceId string) (bool, *v1.NodePool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, clusterId, instanceId)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(*v1.NodePool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Exists indicates an expected call of Exists.
func (mr *MockNodePoolClientMockRecorder) Exists(ctx, clusterId, instanceId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockNodePoolClient)(nil).Exists), ctx, clusterId, instanceId)
}

// Get mocks base method.
func (m *MockNodePoolClient) Get(ctx context.Context, clusterId, instanceId string) (*v1.NodePool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, clusterId, instanceId)
	ret0, _ := ret[0].(*v1.NodePool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockNodePoolClientMockRecorder) Get(ctx, clusterId, instanceId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockNodePoolClient)(nil).Get), ctx, clusterId, instanceId)
}

// List mocks base method.
func (m *MockNodePoolClient) List(ctx context.Context, clusterId string, paging client.Paging) ([]*v1.NodePool, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, clusterId, paging)
	ret0, _ := ret[0].([]*v1.NodePool)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockNodePoolClientMockRecorder) List(ctx, clusterId, paging any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockNodePoolClient)(nil).List), ctx, clusterId, paging)
}

// Update mocks base method.
func (m *MockNodePoolClient) Update(ctx context.Context, clusterId string, instance *v1.NodePool) (*v1.NodePool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, clusterId, instance)
	ret0, _ := ret[0].(*v1.NodePool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockNodePoolClientMockRecorder) Update(ctx, clusterId, instance any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockNodePoolClient)(nil).Update), ctx, clusterId, instance)
}
